---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: oidc-kompass
  namespace: kompass
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: kompass-frontend
  oidc:
    provider:
      issuer: https://auth.cura.nz
    clientID: kompass
    clientSecret:
      name: kompass-secrets
    scopes:
      - openid
      - profile
    cookieNames:
      idToken: IdToken
    forwardAccessToken: true
    redirectURL: https://old.kompa.ss/oauth2/callback
    logoutPath: /logout