---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kompass-frontend
  namespace: kompass
spec:
  interval: 1m0s
  chartRef:
    kind: OCIRepository
    name: frontend
  values:
    controllers:
      kompass-frontend:
        strategy: RollingUpdate

        containers:
          app:
            image:
              repository: ghcr.io/antoncuranz/kompa.ss/frontend
              tag: latest
              pullPolicy: Always
            env:
              MAPBOX_ACCESS_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: kompass-secrets
                    key: MAPBOX_ACCESS_TOKEN

    service:
      app:
        ports:
          http:
            port: 3000
