---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kompass-frontend
  namespace: kompass
spec:
  interval: 1m0s
  chartRef:
    kind: OCIRepository
    name: frontend
  values:
    controllers:
      main:
        strategy: RollingUpdate

        containers:
          main:
            image:
              repository: ghcr.io/antoncuranz/kompa.ss/frontend
              tag: latest
              pullPolicy: Always
            env:
              MAPBOX_ACCESS_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: kompass-secrets
                    key: MAPBOX_ACCESS_TOKEN

      service:
        main:
          ports:
            http:
              port: 3000
