---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 1h
  chart:
    spec:
      chart: kyverno
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kyverno
      version: 3.8.2
  values:
    admissionController:
      replicas: 1
    backgroundController:
      replicas: 1
    reportsController:
      replicas: 1
    crds:
      install: true
