apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubelet-scraper
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubelet-scraper
  namespace: monitoring
rules:
  - apiGroups: [""]
    resources: ["nodes/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubelet-scraper
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: kubelet-scraper
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: kubelet-scraper
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: kubelet-scraper
  namespace: monitoring
spec:
  serviceAccountName: kubelet-scraper
  containers:
    - name: socat
      image: alpine/socat:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          socat TCP-LISTEN:8080,fork TCP:$NODE_IP:10255
      env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
      ports:
        - containerPort: 8080
          name: metrics
  restartPolicy: Always