---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    name: "${APP}-volsync-secret"
    template:
      data:
        RESTIC_REPOSITORY: "s3:{{ `{{ .S3_ENDPOINT }}` }}/paperless-data"
        RESTIC_PASSWORD: "{{ `{{ .RESTIC_PASSWORD }}` }}"
        AWS_ACCESS_KEY_ID: "{{ `{{ .ACCESS_KEY_ID }}` }}"
        AWS_SECRET_ACCESS_KEY: "{{ `{{ .ACCESS_SECRET_KEY }}` }}"
  dataFrom:
    - extract:
        key: b2-volsync