---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: secrets
spec:
  interval: 1m0s
  dependsOn:
    - name: onepassword
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infrastructure/secrets/external-secrets/app
  prune: true
  wait: true
  timeout: 5m0s
