---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: baikal
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      app:
        strategy: RollingUpdate

        containers:
          main:
            image:
              repository: ckulka/baikal
              tag: 0.10.1
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 80
              readiness: *probes
#            securityContext:
#              allowPrivilegeEscalation: false
#              readOnlyRootFilesystem: true
#              capabilities: { drop: [ "ALL" ] }

#    defaultPodOptions:
#      securityContext:
#        runAsNonRoot: true
#        runAsUser: 1000
#        runAsGroup: 1000
#        fsGroup: 1000
#        fsGroupChangePolicy: OnRootMismatch

    service:
      main:
        ports:
          http:
            port: *port

    route:
      main:
        hostnames:
          - baikal.cura.nz
        parentRefs:
          - name: envoy-gateway
            namespace: networking

    persistence:
      data:
        enabled: true
#        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /var/www/baikal/config
            subPath: config
          - path: /var/www/baikal/Specific
            subPath: Specific