---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: baikal
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      app:
        strategy: RollingUpdate

        containers:
          main:
            image:
              repository: ckulka/baikal
              tag: 0.10.0-nginx
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 80
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: [ "ALL" ] }

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch

    service:
      main:
        ports:
          http:
            port: *port

    route:
      main:
        hostnames:
          - baikal.cura.nz
        parentRefs:
          - name: envoy-gateway
            namespace: networking

    persistence:
      data:
        enabled: true
        accessMode: ReadWriteOnce
        defaultMode: 0660
        size: 5Gi
#        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /var/www/baikal/config
            subPath: config
          - path: /var/www/baikal/Specific
            subPath: Specific