---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: authentication
spec:
  interval: 1m0s
  chart:
    spec:
      chart: oauth2-proxy
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
      version: 7.18.0
  values:
    ingress:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "cloudlab.cura.nz"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
      hosts:
        - &host "oauth2.cura.nz"
      tls:
        - secretName: oauth2-tls-certificate
          hosts:
            - *host