---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/monitoring/node-exporter/app
  prune: true
  wait: true
  timeout: 5m0s
