---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: onepassword
  namespace: secrets
spec:
  interval: 1m0s
  url: https://1password.github.io/connect-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword
  namespace: secrets
spec:
  interval: 1m0s
  chart:
    spec:
      chart: connect
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: onepassword
      version: 1.17.1
  values:
    connect:
      serviceType: ClusterIP
      credentialsName: onepassword-secret
      credentialsKey: credentials
    operator:
      create: true
      token:
        name: onepassword-secret
