apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: database-cluster
  namespace: database
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
  superuserSecret:
    name: postgres-secret
  enableSuperuserAccess: true
