---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infrastructure/networking/cert-manager/crds
  - ../../../infrastructure/networking/cert-manager/app.yaml
#  - ../../../infrastructure/networking/cilium/base
#  - ../../../infrastructure/networking/envoy-gateway
# TODO!
patches:
  - target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
    patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: template
      spec:
        prune: true
        wait: true
        interval: 1m0s
        timeout: 5m0s
