---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword
  namespace: secrets
spec:
  interval: 1h
  chart:
    spec:
      chart: connect
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: onepassword
      version: 2.3.0
  values:
    connect:
      serviceType: ClusterIP
      credentialsName: onepassword-secret
      credentialsKey: credentials
    operator:
      create: true
      token:
        name: onepassword-secret
