---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph-cluster
  namespace: storage
spec:
  interval: 1m0s
  dependsOn:
    - name: rook-ceph
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infrastructure/storage/rook-ceph/cluster
  prune: true
  wait: true
  timeout: 5m0s
