---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg
  namespace: database
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infrastructure/database/cloudnative-pg/app
  prune: true
  wait: true
  timeout: 5m0s
