---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-cluster
  namespace: database
spec:
  interval: 1m0s
  dependsOn:
    - name: cloudnative-pg
    - name: external-secrets
      namespace: secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infrastructure/database/cloudnative-pg/cluster
  prune: true
  wait: true
  timeout: 5m0s
