---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: oauth2-proxy
  namespace: authentication
spec:
  interval: 1m0s
  dependsOn:
    - name: pocket-id
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infrastructure/authentication/oauth2-proxy/app
  prune: true
  wait: true
  timeout: 5m0s
