---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ext-postgres-operator
  namespace: database
spec:
  interval: 1m0s
  chart:
    spec:
      chart: ext-postgres-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ext-postgres-operator
      version: 1.2.7
  values:
    existingSecret: ext-postgres-secrets
