---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ext-postgres-operator
  namespace: database
spec:
  interval: 1m0s
  url: https://movetokube.github.io/postgres-operator/
