---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cloudnative-pg-crds
  namespace: database
spec:
  interval: 1h
  ref:
    tag: v1.29.1
  url: https://github.com/cloudnative-pg/cloudnative-pg
