---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: networking
spec:
  path: ./infrastructure/networking/cert-manager/local
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: networking
spec:
  path: ./infrastructure/networking/cilium/local
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: networking
spec:
  path: ./infrastructure/networking/external-dns/local
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: secrets
spec:
  path: ./infrastructure/secrets/external-secrets/local
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: onepassword
  namespace: secrets
spec:
  path: ./infrastructure/secrets/onepassword/local
