---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sync-server
  namespace: kompass
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: sync-server
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/antoncuranz/kompass/sync-server
              tag: 0.19.1

    service:
      main:
        ports:
          http:
            port: 4200

    route:
      main:
        hostnames:
          - sync.kompa.ss
        parentRefs:
          - name: envoy-gateway
            namespace: networking

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
