---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: metrics-basic-auth
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    name: metrics-basic-auth
  dataFrom:
    - extract:
        key: metrics-basic-auth