---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: transportation-api
  namespace: kompass
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/kompass/transportation-api
  prune: true
  wait: true
  timeout: 5m0s
