---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway
  namespace: networking
spec:
  interval: 1h
  dependsOn:
    - name: envoy
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infrastructure/networking/envoy-gateway/gateway
  prune: true
  wait: true
  timeout: 5m0s
