---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      kind: HelmRelease
      name: external-dns
      namespace: networking
    patch: |-
      - op: replace
        path: /spec/values/txtOwnerId
        value: cloudlab-local
      - op: add
        path: /spec/values/domainFilters
        value:
          - local.test
