---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: storage
spec:
  interval: 1m0s
  chart:
    spec:
      chart: rook-ceph-cluster
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rook-ceph-cluster
      version: 1.18.2
  values:
    cephClusterSpec:
      mon:
        allowMultiplePerNode: true
        count: 1
      mgr:
        allowMultiplePerNode: true
        count: 1
