---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-kube-state-metrics
  namespace: monitoring
spec:
  interval: 1m0s
  chart:
    spec:
      chart: kube-state-metrics
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kube-state-metrics
      version: 6.3.0
