---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ext-postgres-operator
  namespace: database
spec:
  interval: 1h
  dependsOn:
    - name: cloudnative-pg-cluster
    - name: onepassword
      namespace: secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infrastructure/database/ext-postgres-operator/app
  prune: true
  wait: true
  timeout: 5m0s
