---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ext-postgres-secrets
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    name: ext-postgres-secrets
  dataFrom:
    - extract:
        key: Ext-Postgres Secrets