---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cert-manager-crds
  namespace: networking
spec:
  interval: 1h
  ref:
    tag: v1.20.3
  url: https://github.com/cert-manager/cert-manager