---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app
  namespace: kompass
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app
  values:
    controllers:
      main:
        strategy: RollingUpdate

        containers:
          main:
            image:
              repository: ghcr.io/antoncuranz/kompass/app
              tag: latest
              pullPolicy: Always
            env:
              JAZZ_SYNC_URL: "http://sync-server.kompass.svc.cluster.local:3000"

    service:
      main:
        ports:
          http:
            port: 3000

    route:
      main:
        hostnames:
          - app.kompa.ss
        parentRefs:
          - name: envoy-gateway
            namespace: networking
