---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app
  namespace: kompass
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app
  values:
    controllers:
      main:
        strategy: RollingUpdate

        containers:
          main:
            image:
              repository: ghcr.io/antoncuranz/kompass/app
              tag: latest
              pullPolicy: Always
            env:
              JAZZ_SYNC_URL: "http://sync-server.kompass.svc.cluster.local:3000"
#            securityContext:
#              allowPrivilegeEscalation: false
#              readOnlyRootFilesystem: true
#              capabilities: { drop: [ "ALL" ] }

#    defaultPodOptions:
#      securityContext:
#        runAsNonRoot: true
#        runAsUser: 1000
#        runAsGroup: 1000
#        fsGroup: 1000
#        fsGroupChangePolicy: OnRootMismatch

    service:
      main:
        ports:
          http:
            port: 80

    route:
      main:
        hostnames:
          - app.kompa.ss
        parentRefs:
          - name: envoy-gateway
            namespace: networking
