---
apiVersion: v1
kind: Service
metadata:
  name: host-metrics
  namespace: monitoring
spec:
  clusterIP: None
  clusterIPs:
    - None
  internalTrafficPolicy: Cluster
  ports:
    - name: kubelet
      port: 10255
      protocol: TCP
      targetPort: 10255
    - name: node-exporter
      port: 9100
      protocol: TCP
      targetPort: 9100
  type: ClusterIP
