---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store
  target:
    name: postgres-secret
  dataFrom:
    - extract:
        key: cloudnative-pg