---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      kind: ClusterIssuer
      name: letsencrypt-prod
    patch: |-
      - op: remove
        path: /spec/acme
      - op: add
        path: /spec/selfSigned
        value: {}
